export default [
  { id: 0, name: "Afghanistan", flag: "🇦🇫", code: "AF", dial_code: "+93" },
  { id: 1, name: "Åland", flag: "🇦🇽", code: "AX", dial_code: "+358" },
  { id: 2, name: "Albanie", flag: "🇦🇱", code: "AL", dial_code: "+355" },
  { id: 3, name: "Algérie", flag: "🇩🇿", code: "DZ", dial_code: "+213" },
  {
    id: 4,
    name: "Samoa américaines",
    flag: "🇦🇸",
    code: "AS",
    dial_code: "+1684",
  },
  { id: 5, name: "Andorre", flag: "🇦🇩", code: "AD", dial_code: "+376" },
  { id: 6, name: "Angola", flag: "🇦🇴", code: "AO", dial_code: "+244" },
  { id: 7, name: "Anguilla", flag: "🇦🇮", code: "AI", dial_code: "+1264" },
  { id: 8, name: "Antarctique", flag: "🇦🇶", code: "AQ", dial_code: "+672" },
  {
    id: 9,
    name: "Antigua-et-Barbuda",
    flag: "🇦🇬",
    code: "AG",
    dial_code: "+1268",
  },
  { id: 10, name: "Argentine", flag: "🇦🇷", code: "AR", dial_code: "+54" },
  { id: 11, name: "Arménie", flag: "🇦🇲", code: "AM", dial_code: "+374" },
  { id: 12, name: "Aruba", flag: "🇦🇼", code: "AW", dial_code: "+297" },
  { id: 13, name: "Australie", flag: "🇦🇺", code: "AU", dial_code: "+61" },
  { id: 14, name: "Autriche", flag: "🇦🇹", code: "AT", dial_code: "+43" },
  { id: 15, name: "Azerbaïdjan", flag: "🇦🇿", code: "AZ", dial_code: "+994" },
  { id: 16, name: "Bahamas", flag: "🇧🇸", code: "BS", dial_code: "+1242" },
  { id: 17, name: "Bahreïn", flag: "🇧🇭", code: "BH", dial_code: "+973" },
  { id: 18, name: "Bangladesh", flag: "🇧🇩", code: "BD", dial_code: "+880" },
  { id: 19, name: "Barbade", flag: "🇧🇧", code: "BB", dial_code: "+1246" },
  { id: 20, name: "Biélorussie", flag: "🇧🇾", code: "BY", dial_code: "+375" },
  { id: 21, name: "Belgique", flag: "🇧🇪", code: "BE", dial_code: "+32" },
  { id: 22, name: "Belize", flag: "🇧🇿", code: "BZ", dial_code: "+501" },
  { id: 23, name: "Bénin", flag: "🇧🇯", code: "BJ", dial_code: "+229" },
  { id: 24, name: "Bermudes", flag: "🇧🇲", code: "BM", dial_code: "+1441" },
  { id: 25, name: "Bhoutan", flag: "🇧🇹", code: "BT", dial_code: "+975" },
  {
    id: 26,
    name: "Bolivia, Plurinational State of bolivia",
    flag: "🇧🇴",
    code: "BO",
    dial_code: "+591",
  },
  {
    id: 27,
    name: "Bosnie-Herzégovine",
    flag: "🇧🇦",
    code: "BA",
    dial_code: "+387",
  },
  { id: 28, name: "Botswana", flag: "🇧🇼", code: "BW", dial_code: "+267" },
  { id: 29, name: "Île Bouvet", flag: "🇧🇻", code: "BV", dial_code: "+47" },
  { id: 30, name: "Brésil", flag: "🇧🇷", code: "BR", dial_code: "+55" },
  {
    id: 31,
    name: "Territoire britannique de l'océan Indien",
    flag: "🇮🇴",
    code: "IO",
    dial_code: "+246",
  },
  { id: 32, name: "Brunei", flag: "🇧🇳", code: "BN", dial_code: "+673" },
  { id: 33, name: "Bulgarie", flag: "🇧🇬", code: "BG", dial_code: "+359" },
  { id: 34, name: "Burkina Faso", flag: "🇧🇫", code: "BF", dial_code: "+226" },
  { id: 35, name: "Burundi", flag: "🇧🇮", code: "BI", dial_code: "+257" },
  { id: 36, name: "Cambodge", flag: "🇰🇭", code: "KH", dial_code: "+855" },
  { id: 37, name: "Cameroun", flag: "🇨🇲", code: "CM", dial_code: "+237" },
  { id: 38, name: "Canada", flag: "🇨🇦", code: "CA", dial_code: "+1" },
  { id: 39, name: "Cape Verde", flag: "🇨🇻", code: "CV", dial_code: "+238" },
  { id: 40, name: "Îles Caïmans", flag: "🇰🇾", code: "KY", dial_code: "+345" },
  {
    id: 41,
    name: "République centrafricaine",
    flag: "🇨🇫",
    code: "CF",
    dial_code: "+236",
  },
  { id: 42, name: "Tchad", flag: "🇹🇩", code: "TD", dial_code: "+235" },
  { id: 43, name: "Chili", flag: "🇨🇱", code: "CL", dial_code: "+56" },
  { id: 44, name: "Chine", flag: "🇨🇳", code: "CN", dial_code: "+86" },
  { id: 45, name: "Île Christmas", flag: "🇨🇽", code: "CX", dial_code: "+61" },
  { id: 46, name: "Îles Cocos", flag: "🇨🇨", code: "CC", dial_code: "+61" },
  { id: 47, name: "Colombie", flag: "🇨🇴", code: "CO", dial_code: "+57" },
  { id: 48, name: "Comores", flag: "🇰🇲", code: "KM", dial_code: "+269" },
  { id: 49, name: "Congo", flag: "🇨🇬", code: "CG", dial_code: "+242" },
  {
    id: 50,
    name: "Congo, The Democratic Republic of the Congo",
    flag: "🇨🇩",
    code: "CD",
    dial_code: "+243",
  },
  { id: 51, name: "Îles Cook", flag: "🇨🇰", code: "CK", dial_code: "+682" },
  { id: 52, name: "Costa Rica", flag: "🇨🇷", code: "CR", dial_code: "+506" },
  { id: 53, name: "Cote d'Ivoire", flag: "🇨🇮", code: "CI", dial_code: "+225" },
  { id: 54, name: "Croatie", flag: "🇭🇷", code: "HR", dial_code: "+385" },
  { id: 55, name: "Cuba", flag: "🇨🇺", code: "CU", dial_code: "+53" },
  { id: 56, name: "Chypre", flag: "🇨🇾", code: "CY", dial_code: "+357" },
  {
    id: 57,
    name: "République tchèque",
    flag: "🇨🇿",
    code: "CZ",
    dial_code: "+420",
  },
  { id: 58, name: "Danemark", flag: "🇩🇰", code: "DK", dial_code: "+45" },
  { id: 59, name: "Djibouti", flag: "🇩🇯", code: "DJ", dial_code: "+253" },
  { id: 60, name: "Dominique", flag: "🇩🇲", code: "DM", dial_code: "+1767" },
  {
    id: 61,
    name: "République dominicaine",
    flag: "🇩🇴",
    code: "DO",
    dial_code: "+1849",
  },
  { id: 62, name: "Équateur", flag: "🇪🇨", code: "EC", dial_code: "+593" },
  { id: 63, name: "Égypte", flag: "🇪🇬", code: "EG", dial_code: "+20" },
  { id: 64, name: "Salvador", flag: "🇸🇻", code: "SV", dial_code: "+503" },
  {
    id: 65,
    name: "Guinée-Équatoriale",
    flag: "🇬🇶",
    code: "GQ",
    dial_code: "+240",
  },
  { id: 66, name: "Érythrée", flag: "🇪🇷", code: "ER", dial_code: "+291" },
  { id: 67, name: "Estonie", flag: "🇪🇪", code: "EE", dial_code: "+372" },
  { id: 68, name: "Éthiopie", flag: "🇪🇹", code: "ET", dial_code: "+251" },
  { id: 69, name: "Îles Malouines", flag: "🇫🇰", code: "FK", dial_code: "+500" },
  { id: 70, name: "Îles Féroé", flag: "🇫🇴", code: "FO", dial_code: "+298" },
  { id: 71, name: "Fidji", flag: "🇫🇯", code: "FJ", dial_code: "+679" },
  { id: 72, name: "Finlande", flag: "🇫🇮", code: "FI", dial_code: "+358" },
  { id: 73, name: "France", flag: "🇫🇷", code: "FR", dial_code: "+33" },
  { id: 74, name: "Guayane", flag: "🇬🇫", code: "GF", dial_code: "+594" },
  {
    id: 75,
    name: "Polynésie française",
    flag: "🇵🇫",
    code: "PF",
    dial_code: "+689",
  },
  {
    id: 76,
    name: "Terres australes et antarctiques françaises",
    flag: "🇹🇫",
    code: "TF",
    dial_code: "+262",
  },
  { id: 77, name: "Gabon", flag: "🇬🇦", code: "GA", dial_code: "+241" },
  { id: 78, name: "Gambie", flag: "🇬🇲", code: "GM", dial_code: "+220" },
  { id: 79, name: "Géorgie", flag: "🇬🇪", code: "GE", dial_code: "+995" },
  { id: 80, name: "Allemagne", flag: "🇩🇪", code: "DE", dial_code: "+49" },
  { id: 81, name: "Ghana", flag: "🇬🇭", code: "GH", dial_code: "+233" },
  { id: 82, name: "Gibraltar", flag: "🇬🇮", code: "GI", dial_code: "+350" },
  { id: 83, name: "Grèce", flag: "🇬🇷", code: "GR", dial_code: "+30" },
  { id: 84, name: "Groenland", flag: "🇬🇱", code: "GL", dial_code: "+299" },
  { id: 85, name: "Grenade", flag: "🇬🇩", code: "GD", dial_code: "+1473" },
  { id: 86, name: "Guadeloupe", flag: "🇬🇵", code: "GP", dial_code: "+590" },
  { id: 87, name: "Guam", flag: "🇬🇺", code: "GU", dial_code: "+1671" },
  { id: 88, name: "Guatemala", flag: "🇬🇹", code: "GT", dial_code: "+502" },
  { id: 89, name: "Guernesey", flag: "🇬🇬", code: "GG", dial_code: "+44" },
  { id: 90, name: "Guinée", flag: "🇬🇳", code: "GN", dial_code: "+224" },
  { id: 91, name: "Guinée-Bissau", flag: "🇬🇼", code: "GW", dial_code: "+245" },
  { id: 92, name: "Guyane", flag: "🇬🇾", code: "GY", dial_code: "+592" },
  { id: 93, name: "Haïti", flag: "🇭🇹", code: "HT", dial_code: "+509" },
  {
    id: 94,
    name: "Heard Island and Mcdonald Islands",
    flag: "🇭🇲",
    code: "HM",
    dial_code: "+672",
  },
  {
    id: 95,
    name: "Holy See (Vatican City State)",
    flag: "🇻🇦",
    code: "VA",
    dial_code: "+379",
  },
  { id: 96, name: "Honduras", flag: "🇭🇳", code: "HN", dial_code: "+504" },
  { id: 97, name: "Hong Kong", flag: "🇭🇰", code: "HK", dial_code: "+852" },
  { id: 98, name: "Hongrie", flag: "🇭🇺", code: "HU", dial_code: "+36" },
  { id: 99, name: "Islande", flag: "🇮🇸", code: "IS", dial_code: "+354" },
  { id: 100, name: "Inde", flag: "🇮🇳", code: "IN", dial_code: "+91" },
  { id: 101, name: "Indonésie", flag: "🇮🇩", code: "ID", dial_code: "+62" },
  {
    id: 102,
    name: "Iran, Islamic Republic of Persian Gulf",
    flag: "🇮🇷",
    code: "IR",
    dial_code: "+98",
  },
  { id: 103, name: "Irak", flag: "🇮🇶", code: "IQ", dial_code: "+964" },
  { id: 104, name: "Irlande", flag: "🇮🇪", code: "IE", dial_code: "+353" },
  { id: 105, name: "Île de Man", flag: "🇮🇲", code: "IM", dial_code: "+44" },
  { id: 106, name: "Israël", flag: "🇮🇱", code: "IL", dial_code: "+972" },
  { id: 107, name: "Italie", flag: "🇮🇹", code: "IT", dial_code: "+39" },
  { id: 108, name: "Jamaïque", flag: "🇯🇲", code: "JM", dial_code: "+1876" },
  { id: 109, name: "Japon", flag: "🇯🇵", code: "JP", dial_code: "+81" },
  { id: 110, name: "Jersey", flag: "🇯🇪", code: "JE", dial_code: "+44" },
  { id: 111, name: "Jordanie", flag: "🇯🇴", code: "JO", dial_code: "+962" },
  { id: 112, name: "Kazakhstan", flag: "🇰🇿", code: "KZ", dial_code: "+7" },
  { id: 113, name: "Kenya", flag: "🇰🇪", code: "KE", dial_code: "+254" },
  { id: 114, name: "Kiribati", flag: "🇰🇮", code: "KI", dial_code: "+686" },
  {
    id: 115,
    name: "Korea, Democratic People's Republic of Korea",
    flag: "🇰🇵",
    code: "KP",
    dial_code: "+850",
  },
  {
    id: 116,
    name: "Korea, Republic of South Korea",
    flag: "🇰🇷",
    code: "KR",
    dial_code: "+82",
  },
  { id: 117, name: "Kosovo", flag: "🇽🇰", code: "XK", dial_code: "+383" },
  { id: 118, name: "Koweït", flag: "🇰🇼", code: "KW", dial_code: "+965" },
  { id: 119, name: "Kirghizistan", flag: "🇰🇬", code: "KG", dial_code: "+996" },
  { id: 120, name: "Laos", flag: "🇱🇦", code: "LA", dial_code: "+856" },
  { id: 121, name: "Lettonie", flag: "🇱🇻", code: "LV", dial_code: "+371" },
  { id: 122, name: "Liban", flag: "🇱🇧", code: "LB", dial_code: "+961" },
  { id: 123, name: "Lesotho", flag: "🇱🇸", code: "LS", dial_code: "+266" },
  { id: 124, name: "Liberia", flag: "🇱🇷", code: "LR", dial_code: "+231" },
  {
    id: 125,
    name: "Libyan Arab Jamahiriya",
    flag: "🇱🇾",
    code: "LY",
    dial_code: "+218",
  },
  { id: 126, name: "Liechtenstein", flag: "🇱🇮", code: "LI", dial_code: "+423" },
  { id: 127, name: "Lituanie", flag: "🇱🇹", code: "LT", dial_code: "+370" },
  { id: 128, name: "Luxembourg", flag: "🇱🇺", code: "LU", dial_code: "+352" },
  { id: 129, name: "Macao", flag: "🇲🇴", code: "MO", dial_code: "+853" },
  { id: 130, name: "Macedonia", flag: "🇲🇰", code: "MK", dial_code: "+389" },
  { id: 131, name: "Madagascar", flag: "🇲🇬", code: "MG", dial_code: "+261" },
  { id: 132, name: "Malawi", flag: "🇲🇼", code: "MW", dial_code: "+265" },
  { id: 133, name: "Malaisie", flag: "🇲🇾", code: "MY", dial_code: "+60" },
  { id: 134, name: "Maldives", flag: "🇲🇻", code: "MV", dial_code: "+960" },
  { id: 135, name: "Mali", flag: "🇲🇱", code: "ML", dial_code: "+223" },
  { id: 136, name: "Malte", flag: "🇲🇹", code: "MT", dial_code: "+356" },
  { id: 137, name: "Îles Marshall", flag: "🇲🇭", code: "MH", dial_code: "+692" },
  { id: 138, name: "Martinique", flag: "🇲🇶", code: "MQ", dial_code: "+596" },
  { id: 139, name: "Mauritanie", flag: "🇲🇷", code: "MR", dial_code: "+222" },
  { id: 140, name: "Île Maurice", flag: "🇲🇺", code: "MU", dial_code: "+230" },
  { id: 141, name: "Mayotte", flag: "🇾🇹", code: "YT", dial_code: "+262" },
  { id: 142, name: "Mexique", flag: "🇲🇽", code: "MX", dial_code: "+52" },
  {
    id: 143,
    name: "Micronesia, Federated States of Micronesia",
    flag: "🇫🇲",
    code: "FM",
    dial_code: "+691",
  },
  { id: 144, name: "Moldova", flag: "🇲🇩", code: "MD", dial_code: "+373" },
  { id: 145, name: "Monaco", flag: "🇲🇨", code: "MC", dial_code: "+377" },
  { id: 146, name: "Mongolie", flag: "🇲🇳", code: "MN", dial_code: "+976" },
  { id: 147, name: "Monténégro", flag: "🇲🇪", code: "ME", dial_code: "+382" },
  { id: 148, name: "Montserrat", flag: "🇲🇸", code: "MS", dial_code: "+1664" },
  { id: 149, name: "Maroc", flag: "🇲🇦", code: "MA", dial_code: "+212" },
  { id: 150, name: "Mozambique", flag: "🇲🇿", code: "MZ", dial_code: "+258" },
  { id: 151, name: "Myanmar", flag: "🇲🇲", code: "MM", dial_code: "+95" },
  { id: 152, name: "Namibie", flag: "🇳🇦", code: "NA", dial_code: "+264" },
  { id: 153, name: "Nauru", flag: "🇳🇷", code: "NR", dial_code: "+674" },
  { id: 154, name: "Népal", flag: "🇳🇵", code: "NP", dial_code: "+977" },
  { id: 155, name: "Pays-Bas", flag: "🇳🇱", code: "NL", dial_code: "+31" },
  {
    id: 156,
    name: "Netherlands Antilles",
    flag: "",
    code: "AN",
    dial_code: "+599",
  },
  {
    id: 157,
    name: "Nouvelle-Calédonie",
    flag: "🇳🇨",
    code: "NC",
    dial_code: "+687",
  },
  {
    id: 158,
    name: "Nouvelle-Zélande",
    flag: "🇳🇿",
    code: "NZ",
    dial_code: "+64",
  },
  { id: 159, name: "Nicaragua", flag: "🇳🇮", code: "NI", dial_code: "+505" },
  { id: 160, name: "Niger", flag: "🇳🇪", code: "NE", dial_code: "+227" },
  { id: 161, name: "Nigéria", flag: "🇳🇬", code: "NG", dial_code: "+234" },
  { id: 162, name: "Niue", flag: "🇳🇺", code: "NU", dial_code: "+683" },
  {
    id: 163,
    name: "Île de Norfolk",
    flag: "🇳🇫",
    code: "NF",
    dial_code: "+672",
  },
  {
    id: 164,
    name: "Îles Mariannes du Nord",
    flag: "🇲🇵",
    code: "MP",
    dial_code: "+1670",
  },
  { id: 165, name: "Norvège", flag: "🇳🇴", code: "NO", dial_code: "+47" },
  { id: 166, name: "Oman", flag: "🇴🇲", code: "OM", dial_code: "+968" },
  { id: 167, name: "Pakistan", flag: "🇵🇰", code: "PK", dial_code: "+92" },
  { id: 168, name: "Palaos", flag: "🇵🇼", code: "PW", dial_code: "+680" },
  {
    id: 169,
    name: "Palestinian Territory, Occupied",
    flag: "🇵🇸",
    code: "PS",
    dial_code: "+970",
  },
  { id: 170, name: "Panama", flag: "🇵🇦", code: "PA", dial_code: "+507" },
  {
    id: 171,
    name: "Papouasie-Nouvelle-Guinée",
    flag: "🇵🇬",
    code: "PG",
    dial_code: "+675",
  },
  { id: 172, name: "Paraguay", flag: "🇵🇾", code: "PY", dial_code: "+595" },
  { id: 173, name: "Pérou", flag: "🇵🇪", code: "PE", dial_code: "+51" },
  { id: 174, name: "Philippines", flag: "🇵🇭", code: "PH", dial_code: "+63" },
  { id: 175, name: "Îles Pitcairn", flag: "🇵🇳", code: "PN", dial_code: "+64" },
  { id: 176, name: "Pologne", flag: "🇵🇱", code: "PL", dial_code: "+48" },
  { id: 177, name: "Portugal", flag: "🇵🇹", code: "PT", dial_code: "+351" },
  { id: 178, name: "Porto Rico", flag: "🇵🇷", code: "PR", dial_code: "+1939" },
  { id: 179, name: "Qatar", flag: "🇶🇦", code: "QA", dial_code: "+974" },
  { id: 180, name: "Roumanie", flag: "🇷🇴", code: "RO", dial_code: "+40" },
  { id: 181, name: "Russia", flag: "🇷🇺", code: "RU", dial_code: "+7" },
  { id: 182, name: "Rwanda", flag: "🇷🇼", code: "RW", dial_code: "+250" },
  { id: 183, name: "Reunion", flag: "🇷🇪", code: "RE", dial_code: "+262" },
  {
    id: 184,
    name: "Saint Barthelemy",
    flag: "🇧🇱",
    code: "BL",
    dial_code: "+590",
  },
  {
    id: 185,
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    flag: "🇸🇭",
    code: "SH",
    dial_code: "+290",
  },
  {
    id: 186,
    name: "Saint-Christophe-et-Niévès",
    flag: "🇰🇳",
    code: "KN",
    dial_code: "+1869",
  },
  { id: 187, name: "Saint-Lucie", flag: "🇱🇨", code: "LC", dial_code: "+1758" },
  { id: 188, name: "Saint Martin", flag: "🇲🇫", code: "MF", dial_code: "+590" },
  {
    id: 189,
    name: "Saint-Pierre-et-Miquelon",
    flag: "🇵🇲",
    code: "PM",
    dial_code: "+508",
  },
  {
    id: 190,
    name: "Saint-Vincent-et-les-Grenadines",
    flag: "🇻🇨",
    code: "VC",
    dial_code: "+1784",
  },
  { id: 191, name: "Samoa", flag: "🇼🇸", code: "WS", dial_code: "+685" },
  { id: 192, name: "Saint-Marin", flag: "🇸🇲", code: "SM", dial_code: "+378" },
  {
    id: 193,
    name: "Sao Tomé-et-Principe",
    flag: "🇸🇹",
    code: "ST",
    dial_code: "+239",
  },
  {
    id: 194,
    name: "Arabie Saoudite",
    flag: "🇸🇦",
    code: "SA",
    dial_code: "+966",
  },
  { id: 195, name: "Sénégal", flag: "🇸🇳", code: "SN", dial_code: "+221" },
  { id: 196, name: "Serbie", flag: "🇷🇸", code: "RS", dial_code: "+381" },
  { id: 197, name: "Seychelles", flag: "🇸🇨", code: "SC", dial_code: "+248" },
  { id: 198, name: "Sierra Leone", flag: "🇸🇱", code: "SL", dial_code: "+232" },
  { id: 199, name: "Singapour", flag: "🇸🇬", code: "SG", dial_code: "+65" },
  { id: 200, name: "Slovaquie", flag: "🇸🇰", code: "SK", dial_code: "+421" },
  { id: 201, name: "Slovénie", flag: "🇸🇮", code: "SI", dial_code: "+386" },
  { id: 202, name: "Îles Salomon", flag: "🇸🇧", code: "SB", dial_code: "+677" },
  { id: 203, name: "Somalie", flag: "🇸🇴", code: "SO", dial_code: "+252" },
  { id: 204, name: "Afrique du Sud", flag: "🇿🇦", code: "ZA", dial_code: "+27" },
  { id: 205, name: "Soudan du Sud", flag: "🇸🇸", code: "SS", dial_code: "+211" },
  {
    id: 206,
    name: "Géorgie du Sud-et-les Îles Sandwich du Sud",
    flag: "🇬🇸",
    code: "GS",
    dial_code: "+500",
  },
  { id: 207, name: "Espagne", flag: "🇪🇸", code: "ES", dial_code: "+34" },
  { id: 208, name: "Sri Lanka", flag: "🇱🇰", code: "LK", dial_code: "+94" },
  { id: 209, name: "Soudan", flag: "🇸🇩", code: "SD", dial_code: "+249" },
  { id: 210, name: "Surinam", flag: "🇸🇷", code: "SR", dial_code: "+597" },
  {
    id: 211,
    name: "Svalbard et Jan Mayen",
    flag: "🇸🇯",
    code: "SJ",
    dial_code: "+47",
  },
  { id: 212, name: "Swaziland", flag: "🇸🇿", code: "SZ", dial_code: "+268" },
  { id: 213, name: "Suède", flag: "🇸🇪", code: "SE", dial_code: "+46" },
  { id: 214, name: "Suisse", flag: "🇨🇭", code: "CH", dial_code: "+41" },
  { id: 215, name: "Syrie", flag: "🇸🇾", code: "SY", dial_code: "+963" },
  { id: 216, name: "Taïwan", flag: "🇹🇼", code: "TW", dial_code: "+886" },
  { id: 217, name: "Tadjikistan", flag: "🇹🇯", code: "TJ", dial_code: "+992" },
  {
    id: 218,
    name: "Tanzania, United Republic of Tanzania",
    flag: "🇹🇿",
    code: "TZ",
    dial_code: "+255",
  },
  { id: 219, name: "Thaïlande", flag: "🇹🇭", code: "TH", dial_code: "+66" },
  {
    id: 220,
    name: "Timor oriental",
    flag: "🇹🇱",
    code: "TL",
    dial_code: "+670",
  },
  { id: 221, name: "Togo", flag: "🇹🇬", code: "TG", dial_code: "+228" },
  { id: 222, name: "Tokelau", flag: "🇹🇰", code: "TK", dial_code: "+690" },
  { id: 223, name: "Tonga", flag: "🇹🇴", code: "TO", dial_code: "+676" },
  {
    id: 224,
    name: "Trinité et Tobago",
    flag: "🇹🇹",
    code: "TT",
    dial_code: "+1868",
  },
  { id: 225, name: "Tunisie", flag: "🇹🇳", code: "TN", dial_code: "+216" },
  { id: 226, name: "Turquie", flag: "🇹🇷", code: "TR", dial_code: "+90" },
  { id: 227, name: "Turkménistan", flag: "🇹🇲", code: "TM", dial_code: "+993" },
  {
    id: 228,
    name: "Îles Turques-et-Caïques",
    flag: "🇹🇨",
    code: "TC",
    dial_code: "+1649",
  },
  { id: 229, name: "Tuvalu", flag: "🇹🇻", code: "TV", dial_code: "+688" },
  { id: 230, name: "Uganda", flag: "🇺🇬", code: "UG", dial_code: "+256" },
  { id: 231, name: "Ukraine", flag: "🇺🇦", code: "UA", dial_code: "+380" },
  {
    id: 232,
    name: "Émirats arabes unis",
    flag: "🇦🇪",
    code: "AE",
    dial_code: "+971",
  },
  { id: 233, name: "United Kingdom", flag: "🇬🇧", code: "GB", dial_code: "+44" },
  { id: 234, name: "United States", flag: "🇺🇸", code: "US", dial_code: "+1" },
  { id: 235, name: "Uruguay", flag: "🇺🇾", code: "UY", dial_code: "+598" },
  { id: 236, name: "Ouzbékistan", flag: "🇺🇿", code: "UZ", dial_code: "+998" },
  { id: 237, name: "Vanuatu", flag: "🇻🇺", code: "VU", dial_code: "+678" },
  {
    id: 238,
    name: "Venezuela, Bolivarian Republic of Venezuela",
    flag: "🇻🇪",
    code: "VE",
    dial_code: "+58",
  },
  { id: 239, name: "Vietnam", flag: "🇻🇳", code: "VN", dial_code: "+84" },
  {
    id: 240,
    name: "Virgin Islands, British",
    flag: "🇻🇬",
    code: "VG",
    dial_code: "+1284",
  },
  {
    id: 241,
    name: "Virgin Islands, U.S.",
    flag: "🇻🇮",
    code: "VI",
    dial_code: "+1340",
  },
  {
    id: 242,
    name: "Wallis-et-Futuna",
    flag: "🇼🇫",
    code: "WF",
    dial_code: "+681",
  },
  { id: 243, name: "Yémen", flag: "🇾🇪", code: "YE", dial_code: "+967" },
  { id: 244, name: "Zambie", flag: "🇿🇲", code: "ZM", dial_code: "+260" },
  { id: 245, name: "Zimbabwe", flag: "🇿🇼", code: "ZW", dial_code: "+263" },
];
